module.exports = {
    CHALLENGEE: 'CHALLENGEE',
    VALIDATOR: 'VALIDATOR',
    GYFTER: 'GYFTER',
    GYFTEE: 'GYFTEE',
    GYFT_EVENT: 'GYFT_EVENT',
    LIQUIDITY_REWARD: 'LIQUIDITY_REWARD',
    EXCHANGE_WITHDRAW: 'EXCHANGE_WITHDRAW',
    EXCHANGE_TRADE: 'EXCHANGE_TRADE',
    MARKET_MAKER_FEE: 'MARKET_MAKER_FEE',
    EOS_ACCOUNT_CREATION_REIMBURSEMENT: 'EOS_ACCOUNT_CREATION_REIMBURSEMENT',
    GYFTER_TO_GYFTEE: 'GYFTER_TO_GYFTEE',
};